import numpy as np

COEFFICIENT_g: float = 9.80665  # gravity (m/s^2)
COEFFICIENT_rho: float = 1.226  # air density at sea level (kg/m^3)
COEFFICIENT_Cd: float = 0.63  # typical for road cyclist
COEFFICIENT_Crr: float = 0.004  # typical for road tires

UPPER_BOUND_HEIGHT_CLAMP_CM	: float	= 250.0
LOWER_BOUND_HEIGHT_CLAMP_CM	: float= 150.0

UPPER_BOUND_WEIGHT_CLAMP_KG	: float = 140.0
LOWER_BOUND_WEIGHT_CLAMP_KG	: float = 40.0

LOWER_BOUND_FRONTAL_AREA_CLAMP = 0.3  # typical frontal area for a road cyclist in m^2. Used as a fallback. The value is based on standard values used in cycling performance modeling. It is not derived from any specific mathematical or domain-specific principle. Typical modern road positions with hands on hoods are closer to 0.35 - 0.38. 0.4 m² is quite large (more like an upright climbing position).


#The above coefficients are based on the physics of cycling and take into account various factors such as air resistance, rolling resistance, and gravitational forces. The values are typical for a road cyclist on flat terrain, and they are used in the calculations to estimate the power required to maintain a certain speed. See jgh_formulae00.py, test01() for details of the speeds measured by ZwiftInsider in August 2023 at 300W and 400W. He is 183cm, and 75kg. The coefficients are not derived from any specific mathematical or domain-specific principle, but rather serve as fixed parameters for the calculations. They are based on empirical measurements and standard values used in cycling performance modeling. The empirical values give excellent results compared in practice, and they are widely accepted in the cycling community.

COEFFICIENT_bike_weight_kg = 8.0 # The standard weight of the bike in kilograms. This is a constant value used in calculations related to the total weight of the rider and bike combination. 

POWER_CURVE_IN_PACELINE = np.array([400, 309, 277, 268, 261, 255, 250, 245], dtype=np.float64) # For all the details of the studies done by Zwift Insider see:- https://zwiftinsider.com/tt-drafting-pd41/ and https://zwiftinsider.com/road-bike-drafting-pd41/ These are summarised in docs/zwiftinsider_stuff.txt. The tests were done in August 2023, measuring Pack Dynamics 4.1. Tests were done in an isolated event on Watopias Tempus Fugit route because its the flattest on Zwift and has a timed section (Fuego Flats Reverse, 7.1km long) which could be used to measure the speeds of each test formation precisely. Zwift Insider did a pair of test - pulling at 300W and 400W respectively. They produced near identical results in terms of percentage saving in the draft. The curve I chose is the TTT curve for pulling @400W for 46.47 kph. I did a thumsuck extrapolation for an additional four riders to cater for an eight person paceline. The overall numbers are not important, only the ratio between them.

PULL_DURATION_OPTIONS_SEC: tuple[float] = [0.0, 30.0, 60.0, 120.0, 180.0, 240.0, 300.0] # NB. the elements MUST BE IN ASCENDING ORDER otherwise the algorithms will not work correctly. The list can be truncated to reduce compute time,maybe to handle larger groups of riders for example, but the values of the elements are fixed, they MUST NOT BE CHANGED otherwise the algorithms will generate nonesense. The values in this array map to the code in RiderBruteItem.get_proxy_pull_watts(..), which in turn maps to the values of RiderBruteItem.get_proxy_30sec_pull_watts(), RiderBruteItem.get_proxy_1_minute_pull_watts(), RiderBruteItem.get_proxy_2_minute_pull_watts(), RiderBruteItem.get_proxy_3_minute_pull_watts(), and RiderBruteItem.get_proxy_4_minute_pull_watts(). These methods are where the magic of curve-fitting comes together with the empirical experience of DaveK as a regular TTT racer. Each method is based parameters for what DaveK feels he can achieve in terms of repeated efforts and over/under intervals in a race. Assuming 8 riders, I recommend max 7 pull periods, otherwise the solution space becomes too large and the algorithm takes too long to compute (more than a minute). The pull periods are in seconds, and they represent the time each rider spends at the front of the paceline during a ride. The first_name element (0.0) is included to represent the case where a rider does not take a pull. The functions affected by PULL_DURATION_OPTIONS_SEC produce the Cartesian product of the allowed pull periods for each rider. For n riders and k allowed pull periods, it generates k^n possible sequences. Each row in the returned array is a sequence of pull periods for the paceline. For instance, six pull periods and eight riders generates 6^8 = 1,679,616 possible sequences. This is a large number, but it is manageable for the algorithm to process within a reasonable time frame, especially with the solution-space pruning applied prior to compute expensive processing. Pruning itself is compute intense, but much less intense than subsequent processing.


DEFAULT_EXERTION_INTENSITY_FACTOR_LIMIT = 1.0 # each team has its own factor depending on the calibre of the team. see class RepositoryOfTeamRosters in Zsun01/src/data_repositories/repository_of_team_rosters.py for details. This is the default factor used when a team does not have a specific factor defined. 


SAFE_LOWER_BOUND_KPH = 10.0 # most TTT paceline speeds will be 35 - 55 kph. round lower bound to to 10 to be safely below all conceivable scenarios.

INITIAL_VELOCITY_GUESS_FOR_NEWTON_SOLVER_KPH = 55 # arbitrary best-guess (on the high side as recommended) of 55 km/h for riders in this domain for Newton-Raphson methods to solve speed from power in jgh_formulae00.solve_for_velocity_from_power(power: float, Cd: float, A: float, Crr: float, total_mass: float, slope: float) -> float: and to solve time taken to complete a specified distance jgh_formulae00.solve_for_duration_riding_solo (rider: RiderComputeItem, distanceKm: float, slope: float = 0.0) -> float: .

REQUIRED_NEWTON_SOLVER_VELOCITY_PRECISION_KPH = 0.01 # The convergence tolerance for the Newton-Raphson root-finding solver used in jgh_formulae00.solve_for_velocity_from_power(...) above. 

REQUIRED_NEWTON_SOLVER_DISTANCE_PRECISION_KM = 1e-3 # The convergence tolerance for the Newton-Raphson root-finding solver used in jgh_formulae00.solve_for_duration_riding_solo (...). The solver finds the duration (seconds) at which the distance residual (km) is zero. This value specifies the acceptable residual error in kilometres. It is not derived from any specific mathematical or domain-specific principle, but rather serves as a practical threshold for numerical convergence. 1e-3 km = 1 meter, which is more than sufficient precision for cycling distance calculations.

CHUNK_OF_KPH_PER_ITERATION = 5.0 # Starting at SAFE_LOWER_BOUND_KPH, the paceline speed is increased by this chunk in each iteration of the binary search. This is an arbitrary value chosen to ensure that the search progresses quickly enough to find a constraint-busting speed within the maximum number of iterations, namely SUFFICIENT_ITERATIONS_TO_GUARANTEE_FINDING_A_SAFE_UPPER_BOUND_KPH. It is not derived from any specific mathematical or domain-specific principle, but rather serves as a practical step size for the search algorithm.


SUFFICIENT_ITERATIONS_TO_GUARANTEE_FINDING_A_SAFE_UPPER_BOUND_KPH = 20 # the ample maximum number of attempts to find the upper bound for the binary search for paceline speed. This is empirically determined and may change with hardware and software improvements. The number is an arbitrary upper limit chosen to prevent the loop from running indefinitely in case a constraint-busting speed is never found. It acts as a safety net to avoid infinite loops.There is no mathematical or domain-specific reason for the value in this context. It is not derived from the number of riders, the range of speeds, or any other parameter. It is simply a "reasonable" number of attempts to find a speed that invalidates at least one rider's . 


REQUIRED_PRECISION_OF_SPEED = 0.05 # The desired precision for the paceline speed binary search algorithm. This is the smallest difference in speed that we consider significant for the purpose of finding a constraint-busting speed. It is not derived from any specific mathematical or domain-specific principle, but rather serves as a practical threshold for determining when to halt the algorithm. The more precise the speed, the more accurate the results will be, but it will also increase the number of iterations required to find a solution. The value is chosen to balance precision and performance, ensuring that the algorithm converges quickly while still providing a meaningful result.


MAX_PERMITTED_ITERATIONS_TO_ACHIEVE_REQUIRED_PRECISION = 30 # Having applied SUFFICIENT_ITERATIONS_TO_GUARANTEE_FINDING_A_SAFE_UPPER_BOUND_KPH Maximum allowable number of iterations for the binary search to find a constraint-busting paceline speed. This is an arbitrary limit chosen to prevent the search from running indefinitely. The algorithm typically takes 10 iterations when commencing from a safe starting base.


SERIAL_TO_PARALLEL_PROCESSING_THRESHOLD = 512 # Below this threshold, serial-processing is faster than parallel-processing.Above this threshold, parallel-processing is faster. The threshold is empirically determined and might be different on different machines with different number physicaland virtual cores. see test01() in formula08.py for details of the determination.

ROTATION_SEQUENCE_UNIVERSE_SIZE_PRUNING_GOAL = 1000 # Emprically researched. See test01() in formula08.py for details of the determination. The sweet zone is 1,000 - 2,500, which keeps compute time within a 7 - 14sec time-frame for up to 6 riders. This constant is an aspirational  target. If the solution space is smaller than 1,000, we do not prune it. We use brute force to analyse and solve the solution space without compromise. If the solution space is more than 1,000, we throw the pruning algorithm at it. The algorithm breaks as soon as the pruned space dips below 1,000. if the algorithm goes all the way and the solution space is still more than 1,000, that's the end of the story. We analyse the space that remains, no matter how time-consuming. The Cartesian cross product of eight riders and seven pull sequences generates a solution space of 5.76 million which takes literally days to compute. The algorithm prunes this down to 3,003 which is manageable (39sec compute time). 

DISTANCE_KM_FOR_PREDICTION = 19.6 # The distance in kilometers for which the predicted duration is calculated. This is a fixed value used in the model to provide a standardized prediction of performance over a specific distance. It is not derived from any specific mathematical or domain-specific principle, but rather serves as a practical benchmark for performance prediction. If you want a base case, 19.6 km is the lead-in to one lap of Tempus Fugit which is a flat TT route on Zwift. 12.44 km is Alpe du Zwift.

SLOPE: float = 0.00  # gradient is the same as slope and is height gained divided by distance travelled on the slope.i.e a fraction. If we were modeling a climb with a 5% slope, we would set SLOPE to 0.05. 8.5% or 0.085 is the slope of Alpe du Zwift. 
